SQLALCHEMY_TRACK_MODIFICATIONS = false
SECRET_KEY = "nAhaMNBaiJcz6H8eWR1oz1xNfFbXMReX"
JWT_ACCESS_LIFESPAN = {hours = 24}
JWT_REFRESH_LIFESPAN = {days = 30}
SBOM_API_ENDPOINT = "http://localhost:4446/analizar_sbom"
